-- IGTrendy 2026 media-platform extension.
-- Existing profiles/categories/prompts are preserved.

create table if not exists public.articles (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text unique not null,
  excerpt text not null default '',
  content_html text not null,
  cover_image_url text,
  category text not null check (category in ('Gaming','Movies','Web Series','Events','Theories','Explained','Trending')),
  tags text[] not null default '{}',
  status text not null default 'draft' check (status in ('draft','published','archived')),
  views bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz
);

create table if not exists public.article_sources (
  id bigint generated by default as identity primary key,
  article_id uuid not null references public.articles(id) on delete cascade,
  title text,
  url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.trend_queue (
  id uuid primary key default gen_random_uuid(),
  topic text not null,
  slug text unique not null,
  category text not null,
  why_now text not null default '',
  status text not null default 'queued' check (status in ('queued','drafted','published','ignored')),
  created_at timestamptz not null default now()
);

create table if not exists public.web_stories (
  id uuid primary key default gen_random_uuid(),
  article_id uuid references public.articles(id) on delete cascade,
  title text not null,
  slides jsonb not null default '[]'::jsonb,
  status text not null default 'draft' check (status in ('draft','published','archived')),
  created_at timestamptz not null default now(),
  published_at timestamptz
);

create table if not exists public.ai_commands (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete set null,
  command text not null,
  mode text not null default 'draft' check (mode in ('draft','publish')),
  status text not null default 'started' check (status in ('started','completed','failed')),
  result jsonb,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists articles_status_published_idx on public.articles(status,published_at desc);
create index if not exists articles_category_idx on public.articles(category,published_at desc);
create index if not exists trend_queue_status_idx on public.trend_queue(status,created_at desc);

alter table public.articles enable row level security;
alter table public.article_sources enable row level security;
alter table public.trend_queue enable row level security;
alter table public.ai_commands enable row level security;
alter table public.web_stories enable row level security;

drop policy if exists "published articles are public" on public.articles;
create policy "published articles are public" on public.articles for select to anon, authenticated using (status='published');

drop policy if exists "published sources are public" on public.article_sources;
create policy "published sources are public" on public.article_sources for select to anon, authenticated using (exists(select 1 from public.articles a where a.id=article_id and a.status='published'));

drop policy if exists "published web stories are public" on public.web_stories;
create policy "published web stories are public" on public.web_stories for select to anon, authenticated using (status='published');

-- Server-side service-role performs AI publishing. Never expose service-role in the browser.

-- Make the existing image bucket capable of storing AI-generated covers too.
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values('prompt-images','prompt-images',true,15728640,array['image/jpeg','image/png','image/webp']::text[])
on conflict(id) do update set public=true,file_size_limit=15728640,allowed_mime_types=excluded.allowed_mime_types;

-- Useful public category seeds for the new site.
insert into public.categories(name,slug,icon) values
('Gaming','gaming','🎮'),('Movies','movies','🎬'),('Web Series','web-series','📺'),('Events','events','🏆'),('Theories','theories','🧠'),('Explained','explained','🔍')
on conflict(name) do update set slug=excluded.slug,icon=excluded.icon;
