-- Promptly database blueprint
-- Run after creating a Supabase project. Review RLS policies before production use.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  full_name text,
  bio text default '',
  avatar_url text,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text unique not null,
  icon text default '',
  slug text unique not null
);

create table if not exists public.prompts (
  id uuid primary key default gen_random_uuid(),
  creator_id uuid references public.profiles(id) on delete set null,
  category_id bigint references public.categories(id) on delete set null,
  title text not null,
  prompt_text text not null,
  image_url text not null,
  status text not null default 'pending' check (status in ('pending','published','rejected')),
  views bigint not null default 0,
  prompt_opens bigint not null default 0,
  copies bigint not null default 0,
  likes bigint not null default 0,
  created_at timestamptz not null default now(),
  published_at timestamptz
);

create table if not exists public.prompt_events (
  id bigint generated by default as identity primary key,
  prompt_id uuid not null references public.prompts(id) on delete cascade,
  event_type text not null check (event_type in ('view','open','copy','like','search')),
  user_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.friend_requests (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','rejected')),
  created_at timestamptz not null default now(),
  unique(sender_id, receiver_id)
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists prompts_status_created_idx on public.prompts(status, created_at desc);
create index if not exists prompts_category_idx on public.prompts(category_id);
create index if not exists prompt_events_prompt_time_idx on public.prompt_events(prompt_id, created_at desc);
create index if not exists messages_pair_time_idx on public.messages(sender_id, receiver_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.prompts enable row level security;
alter table public.prompt_events enable row level security;
alter table public.friend_requests enable row level security;
alter table public.messages enable row level security;

-- Public browsing: only published prompts.
create policy "published prompts are public" on public.prompts
for select to anon, authenticated using (status = 'published');

create policy "users can submit their own prompts" on public.prompts
for insert to authenticated
with check ((select auth.uid()) = creator_id and status = 'pending');

create policy "users can read own profile" on public.profiles
for select to authenticated using ((select auth.uid()) = id);

create policy "profiles are publicly viewable" on public.profiles
for select to anon, authenticated using (true);

create policy "users can update own profile" on public.profiles
for update to authenticated using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

-- Admin publishing should be implemented with a secure server-side admin workflow.
-- Do NOT expose a service-role key in the browser.
