"use client";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { supabase } from "@/lib/supabase";

type Trend = { id:string; topic:string; category:string; why_now:string; trend_score:number; source_urls:string[]; status:string; scanned_at:string|null };
type Article = { id:string; title:string; slug:string; status:string; category:string; created_at:string; updated_at?:string; published_at?:string|null; cover_image_url?:string|null; views?:number };
type Story = { id:string; article_id:string|null; title:string; slides:any[]; status:string; created_at:string; published_at:string|null };
type Stats = { totalArticles:number; publishedArticles:number; draftArticles:number; totalViews:number };

async function readApi(r:Response){const text=await r.text();try{return JSON.parse(text)}catch{throw new Error(`Server returned ${r.status}: ${text.slice(0,220)}`)}}

export default function AdminPage(){
  const [command,setCommand]=useState(""); const [mode,setMode]=useState("draft"); const [loading,setLoading]=useState(false); const [result,setResult]=useState("");
  const [articles,setArticles]=useState<Article[]>([]); const [stories,setStories]=useState<Story[]>([]); const [trends,setTrends]=useState<Trend[]>([]); const [stats,setStats]=useState<Stats>({totalArticles:0,publishedArticles:0,draftArticles:0,totalViews:0});
  const [scanLoading,setScanLoading]=useState(false); const [auth,setAuth]=useState("checking"); const [search,setSearch]=useState("");
  const [editingArticle,setEditingArticle]=useState<any|null>(null); const [editingStory,setEditingStory]=useState<Story|null>(null); const [saveLoading,setSaveLoading]=useState(false); const [deletingId,setDeletingId]=useState("");
  const articleContentRef=useRef<HTMLTextAreaElement|null>(null);

  async function token(){ const {data}=await supabase.auth.getSession(); if(!data.session) throw new Error("Please sign in."); return data.session.access_token; }
  async function load(){
    const t=await token();
    const [tr,content]=await Promise.all([
      fetch("/api/admin/trends/queue",{headers:{Authorization:`Bearer ${t}`},cache:"no-store"}),
      fetch("/api/admin/content",{headers:{Authorization:`Bearer ${t}`},cache:"no-store"})
    ]);
    const tj=await readApi(tr); const cj=await readApi(content);
    if(tr.ok)setTrends(tj.trends||[]); if(content.ok){setArticles(cj.articles||[]);setStories(cj.stories||[]);setStats(cj.stats||stats)}
  }
  useEffect(()=>{(async()=>{try{const{data}=await supabase.auth.getSession();if(!data.session){setAuth("signed-out");return}const{data:isAdmin}=await supabase.rpc("is_igtrendy_admin");const{data:p}=await supabase.from("profiles").select("username,full_name").eq("id",data.session.user.id).maybeSingle();setAuth(isAdmin?`admin:${p?.username||p?.full_name||data.session.user.email||"owner"}:`:`forbidden`);if(isAdmin)await load()}catch{setAuth("forbidden")}})()},[]);

  const filteredArticles=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return articles;return articles.filter(a=>[a.title,a.slug,a.category,a.status].some(v=>String(v||"").toLowerCase().includes(q)))},[articles,search]);
  const publishedArticles=useMemo(()=>filteredArticles.filter(a=>a.status==="published"),[filteredArticles]);
  const draftArticles=useMemo(()=>filteredArticles.filter(a=>a.status==="draft"),[filteredArticles]);
  const totalViews=stats.totalViews || 0;

  function focusSection(id:string){document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"})}
  async function scanNow(){setResult("");setScanLoading(true);try{const t=await token();const r=await fetch("/api/admin/trends",{method:"POST",headers:{Authorization:`Bearer ${t}`}});const j=await readApi(r);if(!r.ok)throw new Error(j.error||"Scan failed");setResult(`✓ Scan complete — ${j.count} trends found.`);await load()}catch(e:any){setResult(`✕ ${e.message}`)}finally{setScanLoading(false)}}
  async function trendAction(id:string,status:string){try{const t=await token();const r=await fetch("/api/admin/trends/queue",{method:"PATCH",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({id,status})});if(!r.ok)throw new Error((await r.json()).error||"Action failed");setTrends(x=>x.filter(t=>t.id!==id))}catch(e:any){setResult(`✕ ${e.message}`)}}
  async function createFromTrend(t:Trend,publish=false){setResult("");setLoading(true);try{const tokenValue=await token();const prompt=`Create ${publish?"and publish":"as a draft"} a substantial original article about this selected IGTrendy trend: ${t.topic}. Category: ${t.category}. Why it is trending: ${t.why_now}. Research the latest reliable information. Use these discovered source URLs as leads, but verify them: ${JSON.stringify(t.source_urls)}. Aim for roughly 1400-2200 words when the topic supports it, with useful context, dates, sections, confirmed vs unconfirmed details, and a concise conclusion. Do not invent facts. Also create 6-10 useful text-only web story slides; images will be added manually later.`;const r=await fetch("/api/ai/command",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${tokenValue}`},body:JSON.stringify({command:prompt,mode:publish?"publish":"draft",generateImage:false,sourceTrendId:t.id})});const j=await readApi(r);if(!r.ok)throw new Error(j.error||"Article generation failed");setResult(`✓ ${j.message} — ${j.article?.title||""} · Images are manual now.`);await load()}catch(e:any){setResult(`✕ ${e.message}`)}finally{setLoading(false)}}
  async function run(){setResult("");if(!command.trim())return;setLoading(true);try{const tokenValue=await token();const r=await fetch("/api/ai/command",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${tokenValue}`},body:JSON.stringify({command,mode,generateImage:false})});const j=await readApi(r);if(!r.ok)throw new Error(j.error||"Command failed");setResult(`✓ ${j.message} — ${j.article?.title||""} · Images are manual now.`);setCommand("");await load()}catch(e:any){setResult(`✕ ${e.message}`)}finally{setLoading(false)}}

  function previewArticle(id:string){window.open(`/admin/articles/${id}/preview`,"_blank","noopener,noreferrer")}
  async function openArticle(id:string){try{setSaveLoading(true);const t=await token();const r=await fetch(`/api/admin/articles/${id}`,{headers:{Authorization:`Bearer ${t}`}});const j=await readApi(r);if(!r.ok)throw new Error(j.error||"Could not open article.");setEditingArticle(j.article)}catch(e:any){setResult(`✕ ${e.message}`)}finally{setSaveLoading(false)}}
  async function saveArticle(){if(!editingArticle)return;setSaveLoading(true);try{const t=await token();const r=await fetch(`/api/admin/articles/${editingArticle.id}`,{method:"PUT",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify(editingArticle)});const j=await readApi(r);if(!r.ok)throw new Error(j.error||"Article save failed.");setResult("✓ Article saved.");setEditingArticle({...editingArticle,...j.article});await load()}catch(e:any){setResult(`✕ ${e.message}`)}finally{setSaveLoading(false)}}
  async function deleteArticle(a:Article){if(!window.confirm(`Delete “${a.title}”? This permanently removes the article and linked web story data. This cannot be undone.`))return;setDeletingId(a.id);try{const t=await token();const r=await fetch(`/api/admin/articles/${a.id}`,{method:"DELETE",headers:{Authorization:`Bearer ${t}`}});const j=await readApi(r);if(!r.ok)throw new Error(j.error||"Article delete failed.");setArticles(x=>x.filter(item=>item.id!==a.id));setStats(s=>({...s,totalArticles:Math.max(0,s.totalArticles-1),publishedArticles:a.status==="published"?Math.max(0,s.publishedArticles-1):s.publishedArticles,draftArticles:a.status==="draft"?Math.max(0,s.draftArticles-1):s.draftArticles}));if(editingArticle?.id===a.id)setEditingArticle(null);setResult(`✓ Deleted: ${a.title}`)}catch(e:any){setResult(`✕ ${e.message}`)}finally{setDeletingId("")}}
  async function uploadImage(file:File){const t=await token();const fd=new FormData();fd.append("file",file);const r=await fetch("/api/admin/media/upload",{method:"POST",headers:{Authorization:`Bearer ${t}`},body:fd});const j=await readApi(r);if(!r.ok)throw new Error(j.error||"Image upload failed.");return j.url as string}
  async function articleImage(file:File,mode:"cover"|"inline"){try{setSaveLoading(true);const url=await uploadImage(file);if(!editingArticle)return;if(mode==="cover"){const updated={...editingArticle,cover_image_url:url};setEditingArticle(updated);const t=await token();const r=await fetch(`/api/admin/articles/${editingArticle.id}`,{method:"PUT",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify(updated)});const j=await readApi(r);if(!r.ok)throw new Error(j.error||"Cover image could not be saved.");setEditingArticle({...updated,...j.article});setResult("✓ Cover image uploaded and saved.");await load()}else{const ta=articleContentRef.current;const tag=`\n<figure><img src="${url}" alt="" loading="lazy" /></figure>\n`;const value=editingArticle.content_html||"";const pos=ta?.selectionStart??value.length;setEditingArticle({...editingArticle,content_html:value.slice(0,pos)+tag+value.slice(pos)});setResult("✓ Image inserted. Save article to keep it.")}}catch(e:any){setResult(`✕ ${e.message}`)}finally{setSaveLoading(false)}}
  async function openStory(id:string){try{setSaveLoading(true);const t=await token();const r=await fetch(`/api/admin/stories/${id}`,{headers:{Authorization:`Bearer ${t}`}});const j=await readApi(r);if(!r.ok)throw new Error(j.error||"Could not open story.");setEditingStory(j.story)}catch(e:any){setResult(`✕ ${e.message}`)}finally{setSaveLoading(false)}}
  async function saveStory(){if(!editingStory)return;setSaveLoading(true);try{const t=await token();const r=await fetch(`/api/admin/stories/${editingStory.id}`,{method:"PUT",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify(editingStory)});const j=await readApi(r);if(!r.ok)throw new Error(j.error||"Story save failed.");setResult("✓ Web story saved.");setEditingStory({...editingStory,...j.story});await load()}catch(e:any){setResult(`✕ ${e.message}`)}finally{setSaveLoading(false)}}
  async function storyImage(index:number,file:File){try{setSaveLoading(true);const url=await uploadImage(file);if(!editingStory)return;const slides=[...(editingStory.slides||[])];slides[index]={...slides[index],image_url:url};setEditingStory({...editingStory,slides});setResult(`✓ Slide ${index+1} image uploaded. Click Save web story.`)}catch(e:any){setResult(`✕ ${e.message}`)}finally{setSaveLoading(false)}}

  if(auth==="checking")return <main className="admin-modern"><div className="admin-loading">Checking Studio access…</div></main>;
  if(auth==="signed-out")return <main className="admin-modern"><div className="admin-loading"><h1>Studio login required</h1><Link href="/login" className="primary-btn">Sign in</Link></div></main>;
  if(auth==="forbidden")return <main className="admin-modern"><div className="admin-loading"><h1>Admin access required</h1><p>Your account is not marked as an admin.</p></div></main>;

  return <main className="admin-modern">
    <header className="admin-top"><Link href="/" className="logo logo-image-link" aria-label="IGTrendy home"><img src="/igtrendy-logo.svg" alt="IGTrendy" className="admin-logo-image" /></Link><div><span>👑 {auth.replace("admin:","").replace(/:$/,"" )}</span><Link href="/">View site</Link></div></header>
    <div className="admin-grid">
      <aside className="admin-side"><div className="eyebrow">STUDIO</div><h2>Control room</h2><nav><a className="active" href="#command-center">🤖 AI Command Center</a><a href="#articles">📝 Articles</a><a href="#drafts">🗒️ Drafts</a><a href="#stories">📱 Web Stories</a><a href="#scanned-trends">🔥 Scanned Trends</a><a href="#analytics">📊 Analytics</a></nav><div className="safety-box"><b>AI workflow</b><p>AI writes article and story text. Images stay manual so you control every visual.</p></div></aside>
      <section className="admin-main">
        <div id="command-center" className="command-panel"><div className="eyebrow">AI COMMAND CENTER</div><h1>What should IGTrendy cover next?</h1><p className="lead">Scan current trends, then choose exactly what becomes a draft or published article.</p></div>
        <div id="scanned-trends" className="eyebrow">SCANNED TRENDS</div><div className="trend-head"><div><h1>Choose what deserves an article.</h1><p className="lead">The scanner only queues trends. Gemini writes the long-form article and text-only web story. No AI image generation is called.</p></div><button className="primary-btn" onClick={scanNow} disabled={scanLoading}>{scanLoading?"Scanning…":"🔎 Scan now"}</button></div>
        {result&&<div className={`command-result ${result.startsWith("✕")?"bad":""}`}>{result}</div>}
        <div className="trend-list">{trends.length===0?<div className="empty-state"><b>No queued trends yet.</b><span>Run a scan to discover current gaming, movie, web-series and event topics.</span></div>:trends.map(t=><article className="trend-card" key={t.id}><div className="trend-score">{t.trend_score}<small>/100</small></div><div className="trend-main"><div className="trend-meta"><span>{t.category}</span><span>{t.scanned_at?new Date(t.scanned_at).toLocaleString():"New"}</span></div><h3>{t.topic}</h3><p>{t.why_now}</p><div className="trend-sources">{(t.source_urls||[]).slice(0,3).map((u,i)=><a key={i} href={u} target="_blank" rel="noreferrer">Source {i+1} ↗</a>)}</div><div className="trend-actions"><button className="primary-btn" disabled={loading} onClick={()=>createFromTrend(t,false)}>📝 Create draft</button><button className="secondary-btn" disabled={loading} onClick={()=>createFromTrend(t,true)}>🚀 Create & publish</button><button className="ghost-btn" onClick={()=>trendAction(t.id,"ignored")}>Ignore</button></div></div></article>)}</div>
        <div className="command-divider"><div className="eyebrow">MANUAL COMMAND</div><h2>AI Command Center</h2></div><textarea className="command-textarea" value={command} onChange={e=>setCommand(e.target.value)} placeholder="Example: Research the latest GTA 6 update and create a detailed original article with sources and a text-only web story."/><div className="command-actions"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="draft">Save as draft</option><option value="publish">Publish automatically</option></select><button className="primary-btn" onClick={run} disabled={loading}>{loading?"AI is working…":"Run command →"}</button></div>
        <div className="quick-commands"><button onClick={()=>setCommand("Find the biggest useful gaming trend today and save a detailed 1400-2200 word original article as a draft with sources and a text-only web story.")}>🎮 Gaming trend</button><button onClick={()=>setCommand("Find the most important movie or web-series update today and save a detailed factual article as a draft with sources and a text-only web story.")}>🎬 Entertainment trend</button><button onClick={()=>setCommand("Find a major upcoming global event worth covering and create a detailed useful guide as a draft with dates, reliable sources and a text-only web story.")}>🏆 Event guide</button></div>

        <section id="analytics" className="admin-overview"><div className="overview-title"><div><div className="eyebrow">PUBLISHING OVERVIEW</div><h2>IGTrendy at a glance</h2></div><button className="ghost-btn" onClick={()=>load()}>↻ Refresh</button></div><div className="overview-grid"><div className="overview-card"><span>Total articles</span><strong>{stats.totalArticles}</strong><small>All statuses</small></div><div className="overview-card"><span>Published</span><strong>{stats.publishedArticles}</strong><small>Live on the public site</small></div><div className="overview-card"><span>Drafts</span><strong>{stats.draftArticles}</strong><small>Waiting for editing</small></div><div className="overview-card"><span>Total article views</span><strong>{totalViews.toLocaleString()}</strong><small>Tracked browser-session views</small></div></div></section>

        <section id="articles" className="recent article-manager"><div className="section-title"><div><div className="eyebrow">CONTENT LIBRARY</div><h2>Articles</h2><p className="manager-subtitle">Search, edit, preview or delete any article without hunting through the page.</p></div><Link href="/trending">Public site →</Link></div><div className="article-toolbar"><div className="article-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search title, category, slug…"/><kbd>⌘ K</kbd></div><div className="article-filter-summary">{filteredArticles.length} shown · {publishedArticles.length} published · {draftArticles.length} drafts</div></div>{filteredArticles.length===0?<div className="empty-state">No articles match “{search}”.</div>:<div className="article-table"><div className="article-table-head"><span>ARTICLE</span><span>STATUS</span><span>VIEWS</span><span>UPDATED</span><span>ACTIONS</span></div>{filteredArticles.map(a=><div className="article-row-admin" key={a.id}><div className="article-cell-main"><div className="article-thumb">{a.cover_image_url?<img src={a.cover_image_url} alt=""/>:<span>{a.category?.slice(0,1)||"✦"}</span>}</div><div><b title={a.title}>{a.title}</b><small>{a.category} · /article/{a.slug}</small></div></div><div><span className={`status-pill ${a.status}`}>{a.status}</span></div><div className="views-cell">◉ {Number(a.views||0).toLocaleString()}</div><div className="updated-cell">{new Date(a.updated_at||a.created_at).toLocaleDateString()}</div><div className="admin-row-actions compact"><button className="secondary-btn" onClick={()=>openArticle(a.id)}>✏️ Edit</button><button className="ghost-btn" onClick={()=>previewArticle(a.id)}>👁️</button>{a.status==="published"&&<Link className="table-link" href={`/article/${a.slug}`}>Open</Link>}<button className="delete-btn" disabled={deletingId===a.id} onClick={()=>deleteArticle(a)}>{deletingId===a.id?"Deleting…":"Delete"}</button></div></div>)}</div>}</section>

        <section id="drafts" className="recent"><div className="section-title"><div><div className="eyebrow">DRAFTS</div><h2>Draft queue</h2></div><span>{stats.draftArticles} drafts</span></div>{draftArticles.length?<div className="compact-draft-grid">{draftArticles.map(a=><button className="draft-card" key={a.id} onClick={()=>openArticle(a.id)}><span className="status-pill draft">DRAFT</span><b>{a.title}</b><small>{a.category} · {Number(a.views||0).toLocaleString()} views</small><em>Click to open editor →</em></button>)}</div>:<div className="empty-state"><p>No matching drafts. Create one from Scanned Trends.</p></div>}</section>

        <section id="stories" className="recent"><div className="section-title"><div><div className="eyebrow">STORY EDITOR</div><h2>Web Stories</h2></div><Link href="/stories">Public stories →</Link></div>{stories.length===0?<div className="empty-state">No web stories yet. Generate an article first.</div>:<div className="compact-story-grid">{stories.map(s=><div className="story-admin-card" key={s.id}><div><span className="status-pill">{s.status}</span><b>{s.title}</b><small>{(s.slides||[]).length} slides · images can be added per slide</small></div><button className="secondary-btn" onClick={()=>openStory(s.id)}>Edit story</button></div>)}</div>}</section>
      </section>
    </div>

    {editingArticle&&<div className="editor-modal-backdrop" role="dialog" aria-modal="true" onMouseDown={e=>{if(e.target===e.currentTarget)setEditingArticle(null)}}><section className="editor-modal"><div className="editor-head"><div><div className="eyebrow">ARTICLE EDITOR</div><h2>{editingArticle.title}</h2><span className="editor-meta">{editingArticle.status} · {Number(editingArticle.views||0).toLocaleString()} views</span></div><div className="admin-row-actions"><button className="ghost-btn" onClick={()=>previewArticle(editingArticle.id)}>👁️ Preview</button><button className="ghost-btn" onClick={()=>setEditingArticle(null)}>✕ Close</button></div></div><label>Title<input value={editingArticle.title||""} onChange={e=>setEditingArticle({...editingArticle,title:e.target.value})}/></label><label>Excerpt<textarea value={editingArticle.excerpt||""} onChange={e=>setEditingArticle({...editingArticle,excerpt:e.target.value})}/></label><label>Cover image URL<input value={editingArticle.cover_image_url||""} onChange={e=>setEditingArticle({...editingArticle,cover_image_url:e.target.value})} placeholder="Upload below or paste a public image URL"/></label><div className="editor-tools"><label className="upload-mini">🖼️ Upload cover<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)articleImage(f,"cover")}}/></label><label className="upload-mini">➕ Upload & insert image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)articleImage(f,"inline")}}/></label></div>{editingArticle.cover_image_url&&<img className="editor-cover-preview" src={editingArticle.cover_image_url} alt="Cover preview"/>}<label>Article HTML<textarea ref={articleContentRef} className="editor-content" value={editingArticle.content_html||""} onChange={e=>setEditingArticle({...editingArticle,content_html:e.target.value})}/></label><p className="editor-help">Inline images can be inserted at the current cursor position. Save when finished.</p><div className="editor-actions"><select value={editingArticle.status||"draft"} onChange={e=>setEditingArticle({...editingArticle,status:e.target.value})}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select><button className="delete-btn large" onClick={()=>deleteArticle(editingArticle)}>Delete article</button><button className="primary-btn" disabled={saveLoading} onClick={saveArticle}>{saveLoading?"Saving…":"Save article"}</button></div></section></div>}

    {editingStory&&<div className="editor-modal-backdrop" role="dialog" aria-modal="true" onMouseDown={e=>{if(e.target===e.currentTarget)setEditingStory(null)}}><section className="editor-modal story-modal"><div className="editor-head"><div><div className="eyebrow">WEB STORY EDITOR</div><h2>{editingStory.title}</h2></div><button className="ghost-btn" onClick={()=>setEditingStory(null)}>✕ Close</button></div><label>Story title<input value={editingStory.title||""} onChange={e=>setEditingStory({...editingStory,title:e.target.value})}/></label><div className="story-editor-list">{(editingStory.slides||[]).map((slide:any,i:number)=><div className="story-editor-slide" key={i}><div className="story-slide-num">Slide {i+1}</div><label>Headline<input value={slide.headline||""} onChange={e=>{const slides=[...editingStory.slides];slides[i]={...slides[i],headline:e.target.value};setEditingStory({...editingStory,slides})}}/></label><label>Text<textarea value={slide.body||""} onChange={e=>{const slides=[...editingStory.slides];slides[i]={...slides[i],body:e.target.value};setEditingStory({...editingStory,slides})}}/></label><label>Image URL<input value={slide.image_url||""} onChange={e=>{const slides=[...editingStory.slides];slides[i]={...slides[i],image_url:e.target.value};setEditingStory({...editingStory,slides})}} placeholder="Optional — upload below or paste a public URL"/></label><label className="upload-mini">🖼️ Upload slide image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)storyImage(i,f)}}/></label>{slide.image_url&&<img className="story-editor-image" src={slide.image_url} alt="Slide"/>}</div>)}</div><div className="editor-actions"><select value={editingStory.status||"draft"} onChange={e=>setEditingStory({...editingStory,status:e.target.value})}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select><button className="primary-btn" disabled={saveLoading} onClick={saveStory}>{saveLoading?"Saving…":"Save web story"}</button></div></section></div>}
  </main>
}
