export type Prompt = { id:string; title:string; category:string; creator:string; username:string; image:string; views:number; likes:number; tags:string[]; prompt:string };
export const prompts: Prompt[] = [
["80s-retro-portrait","80s Retro Indian Portrait","Retro / Vintage","Prince JNVian","princejnvian","https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=85",8420,1280,["80s","retro","portrait","india"],"Create a photorealistic 1980s Indian studio portrait of a young man, preserving natural facial proportions and realistic skin texture. Use authentic 80s clothing, warm analog film grain, slightly faded colors, soft flash photography, vintage Indian photo-studio background, subtle lens imperfections, realistic shadows, candid expression, 35mm film aesthetic, high detail, no modern objects, no text."],
["cinematic-night","Cinematic Night Portrait","Cinematic","Aarav Studio","aaravstudio","https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=85",6910,930,["cinematic","portrait","night"],"Create a cinematic night portrait with realistic skin texture, controlled rim light, shallow depth of field, moody atmosphere, subtle film grain, natural expression, premium color grading and realistic photographic detail."],
["retro-couple","Vintage 80s Couple","Retro / Vintage","Maya AI","mayaai","https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=85",6150,840,["80s","couple","vintage"],"Create a realistic 1980s Indian couple portrait, authentic period clothing, analog 35mm film texture, warm tones, vintage studio lighting and natural expressions."],
["fashion-editorial","Editorial Fashion Portrait","Fashion","FrameLab","framelab","https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=85",5430,720,["fashion","editorial"],"Create a premium editorial fashion portrait with studio lighting, realistic fabric texture, confident pose, clean composition and high-end magazine photography."],
["travel-film","35mm Travel Film Look","Travel","Riya Creates","riyacreates","https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85",4980,610,["travel","film","35mm"],"Create a candid travel photograph with authentic 35mm film grain, natural sunlight, subtle imperfections, realistic colors and documentary-style composition."],
["wedding-editorial","Luxury Wedding Editorial","Wedding","Studio K","studiok","https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=900&q=85",4630,580,["wedding","luxury"],"Create a luxurious Indian wedding editorial photograph with elegant styling, soft cinematic lighting, realistic skin and fabric detail, shallow depth of field and premium photography."],
["anime-character","Cinematic Anime Character","Anime / Artistic","Kaito AI","kaitoai","https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=900&q=85",4380,550,["anime","character"],"Create a detailed cinematic anime character portrait with expressive eyes, dramatic lighting, rich environmental detail and polished illustration quality."],
["professional-headshot","Premium Professional Headshot","Professional","PixelPro","pixelpro","https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=85",3970,480,["professional","headshot"],"Create a premium professional headshot with realistic skin texture, clean studio lighting, subtle background blur and natural confident expression."],
["instagram-glow","Instagram Golden Hour","Instagram Photos","Nisha Visuals","nishavisuals","https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=85",3820,450,["instagram","golden hour"],"Create an Instagram-ready golden-hour portrait with warm natural light, realistic skin, soft background bokeh and an authentic candid feeling."],
["character-warrior","Fantasy Warrior Character","Character Creation","Concept AI","conceptai","https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=900&q=85",3610,420,["fantasy","warrior"],"Create an original fantasy warrior character with cinematic armor details, dramatic lighting, realistic materials and a powerful but natural pose."],
["before-after","Portrait Transformation","Before / After","EditVerse","editverse","https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=900&q=85",3320,390,["before-after","portrait"],"Transform the portrait while keeping the person's identity recognizable. Improve lighting, composition and image quality while retaining realistic facial proportions."],
["ai-beauty","Soft AI Beauty Portrait","AI Portraits","Zoya AI","zoyaai","https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=85",3190,360,["portrait","beauty"],"Create a soft editorial beauty portrait with realistic skin texture, gentle natural lighting, subtle depth of field and refined photographic detail."]
].map(x=>({id:x[0],title:x[1],category:x[2],creator:x[3],username:x[4],image:x[5],views:x[6],likes:x[7],tags:x[8],prompt:x[9]} as Prompt));
export const categories=["🔥 Viral / Trending","👤 AI Portraits","📸 Instagram Photos","🎬 Cinematic","🕰️ Retro / Vintage","💍 Wedding","👔 Fashion","🧑‍💼 Professional","🎨 Anime / Artistic","🏞️ Travel","🏆 Before / After","🎭 Character Creation"];
